---
# tasks file for ansible-storage-drivers
- name: Install ceph packages for rhel
  action: "{{ ansible_pkg_mgr }}"
  args:
  name: "{{ item }}"
  state: latest
  with_items:
    - "{{ storage_drivers_ceph_packages_rhel }}"
  when: ansible_distribution != "Debian" and ansible_distribution != "Ubuntu"

- name: Install ceph packages for deb
  action: "{{ ansible_pkg_mgr }}"
  args:
    name: "{{ item }}"
    state: latest
  with_items:
    - "{{ storage_drivers_ceph_packages_deb }}"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
